name: Build and Test Transusite

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_test_artifact:
    name: Build and Test Transusite

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restore NuGet packages
      run: dotnet restore

    - name: Build solution
      run: dotnet build --configuration Release --no-restore

    - name: Test solution
      run: dotnet test --configuration Release --no-build --verbosity normal

    - name: Publish artifact
      run: dotnet publish -c Release -o published

    - name: Upload artifact for web
      uses: actions/upload-artifact@v2
      with:
        name: transusite
        path: published/wwwroot
